"""Build gen_s3d_page_zh.py from gen_s3d_page.py: same computation, Chinese visible text (user 2026-09-30).
Every replacement must match exactly once."""
from pathlib import Path
HERE = Path(__file__).parent
src = (HERE / "gen_s3d_page.py").read_text()

R = []
def rep(old, new, n=1):
    R.append((old, new, n))

rep('"""3-D solvent charge report page (user request 2026-09-30) from the outputs of solvent3d_full_eval.py.',
    '"""3-D solvent charge report page, CHINESE text (generated by make_zh_generator.py from gen_s3d_page.py).')
rep('CHN = {"b": "bound", "i": "ionic", "t": "total"}',
    'CHN = {"b": "束缚电荷", "i": "离子电荷", "t": "合计"}\n'
    'GNAME = {"NiN44 charged": "NiN44 带电", "NiN88 charged": "NiN88 带电", "NiN44 solvated neutral": "NiN44 中性带溶剂"}\n'
    'SPNAME = {"val": "验证集", "test": "测试集", "train": "训练集"}')
rep('ACOL = {"C"',
    'import matplotlib.font_manager as _fm\n'
    '_fm.fontManager.ttflist.append(_fm.FontEntry(fname="/usr/share/fonts/google-droid/DroidSansFallback.ttf", name="CJKFallback",\n'
    '                                             style="normal", variant="normal", weight=400, stretch="normal", size="scalable"))\n'
    'plt.rcParams["font.family"] = ["DejaVu Sans", "CJKFallback"]\n'
    'SPN = SPNAME.get(SPLIT, SPLIT)\n'
    'ACOL = {"C"')
# figures
rep('ax.set_ylabel("x along a (Å)")', 'ax.set_ylabel("沿 a 方向的 x (Å)")')
rep('ax.set_title(f"{nm}: surfaces at +{L:.2e} (red) and −{L:.2e} (blue) e/Å³", loc="left", fontsize=13)',
    'ax.set_title(f"{nm}：+{L:.2e}（红）与 −{L:.2e}（蓝）e/Å³ 等值面", loc="left", fontsize=13)')
rep('label=f"{g}: DFT |ρ| (n = {len(sids)})")', 'label=f"{GNAME[g]}：DFT |ρ|（n = {len(sids)}）")')
rep('label=f"{g}: |ML − DFT|")', 'label=f"{GNAME[g]}：|ML − DFT|")')
rep('ax.set_ylabel("plane integral (e/Å)")', 'ax.set_ylabel("平面积分 (e/Å)")')
rep('ax.set_title(f"{CHN[ch]} charge: plane-integrated absolute error per z plane, mean over {SPLIT} frames", loc="left")',
    'ax.set_title(f"{CHN[ch]}：每个 z 平面上绝对误差的平面积分，{SPN}各帧平均", loc="left")')
rep('label=f"{SPLIT} pairs (n = {len(prs)})" if k == 0 else None)', 'label=f"{SPN}配对（n = {len(prs)}）" if k == 0 else None)')
rep('''label=f"sid {p['sid_c']} / {p['sid_n']} (test)" if k == 0 else None)''',
    '''label=f"sid {p['sid_c']} / {p['sid_n']}（{SPNAME.get(p['split'], p['split'])}）" if k == 0 else None)''')
rep('ax.set_xticklabels(["bound Δρ", "ionic Δρ", "total Δρ"])', 'ax.set_xticklabels(["束缚电荷 Δρ", "离子电荷 Δρ", "合计 Δρ"])')
rep('ax.set_ylabel("ε₃D of Δρ = ρ(charged) − ρ(neutral)")', 'ax.set_ylabel("Δρ = ρ(带电) − ρ(中性) 的 ε₃D")')
# tables
rep('stat_rows.append([f"{g} · {CHN[ch]}", len(rs), "— (reference ≈ 0)"', 'stat_rows.append([f"{GNAME[g]} · {CHN[ch]}", len(rs), "—（参考值 ≈ 0）"')
rep('tbl_stats = table(["frames · channel", "n", "ε₃D median [min–max]", "ε⊥ median", "ε plane-avg median", "∫|ML−DFT| median (e)",\n'
    '                   "∫|DFT| median (e)", "net error mean / rms (e)", "RMSE median (e/Å³)"], stat_rows)',
    'tbl_stats = table(["帧组 · 通道", "n", "ε₃D 中位数 [最小–最大]", "ε⊥ 中位数", "ε 平面平均 中位数", "∫|ML−DFT| 中位数 (e)",\n'
    '                   "∫|DFT| 中位数 (e)", "净电荷误差 均值 / rms (e)", "RMSE 中位数 (e/Å³)"], stat_rows)')
rep('pair_rows.append([f"{SPLIT} pairs · {CHN[ch]} Δρ"', 'pair_rows.append([f"{SPN}配对 · {CHN[ch]} Δρ"')
rep('''pair_rows.append([f"sid {p['sid_c']} / {p['sid_n']} ({p['split']}) · {CHN[ch]} Δρ"''',
    '''pair_rows.append([f"sid {p['sid_c']} / {p['sid_n']}（{SPNAME.get(p['split'], p['split'])}）· {CHN[ch]} Δρ"''')
rep('tbl_pairs = table(["pairs · channel", "n", "ε₃D median [min–max]", "ε⊥ median", "∫|ΔML−ΔDFT| median (e)", "∫|ΔDFT| median (e)",\n'
    '                   "net ΔDFT mean (e)", "net error mean / rms (e)"], pair_rows)',
    'tbl_pairs = table(["配对 · 通道", "n", "ε₃D 中位数 [最小–最大]", "ε⊥ 中位数", "∫|ΔML−ΔDFT| 中位数 (e)", "∫|ΔDFT| 中位数 (e)",\n'
    '                   "ΔDFT 净电荷 均值 (e)", "净电荷误差 均值 / rms (e)"], pair_rows)')
rep('''rep_rows.append([{"median": "median-error frame", "max": "highest-error frame", "pair_page": "pair-page frame"}[role], sid, r["group"], r["split"],''',
    '''rep_rows.append([{"median": "误差中位帧", "max": "误差最大帧", "pair_page": "配对页的帧"}[role], sid, GNAME[r["group"]], SPNAME.get(r["split"], r["split"]),''')
rep('tbl_rep = table(["role", "sid", "frames", "split", "ε₃D bound", "ε₃D ionic", "ε₃D total", "ε⊥ bound", "bound peak plane z (Å)", "ionic peak plane z (Å)"], rep_rows)',
    'tbl_rep = table(["角色", "sid", "帧组", "划分", "ε₃D 束缚", "ε₃D 离子", "ε₃D 合计", "ε⊥ 束缚", "束缚电荷峰值平面 z (Å)", "离子电荷峰值平面 z (Å)"], rep_rows)')
rep('cats3 = [("NiN44 ch.\\nbound", "NiN44 charged", "b"), ("NiN88 ch.\\nbound", "NiN88 charged", "b"), ("neutral\\nbound", "NiN44 solvated neutral", "b"),\n'
    '         ("NiN44 ch.\\nionic", "NiN44 charged", "i"), ("NiN88 ch.\\nionic", "NiN88 charged", "i"), ("neutral\\nionic", "NiN44 solvated neutral", "i"),\n'
    '         ("NiN44 ch.\\ntotal", "NiN44 charged", "t"), ("NiN88 ch.\\ntotal", "NiN88 charged", "t"), ("neutral\\ntotal", "NiN44 solvated neutral", "t")]',
    'cats3 = [("NiN44 带电\\n束缚", "NiN44 charged", "b"), ("NiN88 带电\\n束缚", "NiN88 charged", "b"), ("中性\\n束缚", "NiN44 solvated neutral", "b"),\n'
    '         ("NiN44 带电\\n离子", "NiN44 charged", "i"), ("NiN88 带电\\n离子", "NiN88 charged", "i"), ("中性\\n离子", "NiN44 solvated neutral", "i"),\n'
    '         ("NiN44 带电\\n合计", "NiN44 charged", "t"), ("NiN88 带电\\n合计", "NiN88 charged", "t"), ("中性\\n合计", "NiN44 solvated neutral", "t")]')
rep('FIGS["epslat"] = strip_figure("eps_lat", "ε⊥ (lateral part)", cats3)', 'FIGS["epslat"] = strip_figure("eps_lat", "ε⊥（横向部分）", cats3)')
rep('FIGS["neterr"] = strip_figure("net_err_e", "net charge error ∫(ML−DFT) dV (e)", catsn, signed=True)',
    'FIGS["neterr"] = strip_figure("net_err_e", "净电荷误差 ∫(ML−DFT) dV (e)", catsn, signed=True)')
rep(r'''    "delta": tex(r"$\Delta\rho=\rho^{charged}-\rho^{neutral}\qquad(\mathrm{same\ geometry,\ both\ models\ and\ DFT})$"),''',
    r'''    "delta": tex(r"$\Delta\rho=\rho^{(q)}-\rho^{(0)}$"),''')
# notes
rep('''    return (f"Shown z window {i['z0']:.1f}–{i['z1']:.1f} Å (where the DFT charge is above 1 % of its peak). Colour scale of the DFT and ML "
            f"rows: ±{i['v']:.2e} e/Å³ (99.9th percentile of |ρ| on this slice, both rows); error row ±{i['ve']:.2e} e/Å³. "
            f"Largest |DFT| on the slice {i['dmax']:.2e}, largest |error| {i['emax']:.2e} e/Å³. Atoms within 1 Å of the plane are drawn.")''',
    '''    return (f"显示的 z 范围 {i['z0']:.1f}–{i['z1']:.1f} Å：DFT 电荷超过其峰值 1% 的区域，并包含 Ni 原子下方 2 Å。DFT 行和 ML 行共用色标 "
            f"±{i['v']:.2e} e/Å³，取该切片上两行 |ρ| 的 99.9 百分位；误差行色标 ±{i['ve']:.2e} e/Å³。"
            f"切片上 |DFT| 最大 {i['dmax']:.2e}，|误差| 最大 {i['emax']:.2e} e/Å³。图中画出距切面 1 Å 以内的原子。")''')
rep('''    s = (f"Plane z = {i['z']:.2f} Å, shown on one rectangular periodic cell. Plane means: DFT {i['mean_dft']:+.2e}, ML {i['mean_ml']:+.2e} e/Å³"
         + (" (removed in both rows)." if lateral else ".")
         + f" Colour scale DFT/ML ±{i['v']:.2e}, error ±{i['ve']:.2e} e/Å³. Atoms within 1 Å of the plane are drawn.")''',
    '''    s = (f"平面 z = {i['z']:.2f} Å，画在一个矩形周期晶胞上。平面平均值：DFT {i['mean_dft']:+.2e}，ML {i['mean_ml']:+.2e} e/Å³"
         + ("，两行都已减去。" if lateral else "。")
         + f"色标 DFT/ML ±{i['v']:.2e}，误差 ±{i['ve']:.2e} e/Å³。图中画出距该平面 1 Å 以内的原子。")''')
rep('''LEVTXT = (f"+{INFO['iso_levels'][0]:.2e} / −{INFO['iso_levels'][0]:.2e} e/Å³ for DFT and ML, ±{INFO['iso_levels'][1]:.2e} e/Å³ for the error"''',
    '''LEVTXT = (f"DFT 与 ML 为 +{INFO['iso_levels'][0]:.2e} / −{INFO['iso_levels'][0]:.2e} e/Å³，误差为 ±{INFO['iso_levels'][1]:.2e} e/Å³"''')

out = src
for old, new, n in R:
    c = out.count(old)
    assert c == n, (c, old[:90])
    out = out.replace(old, new)

# the page template: replace the whole f-string block
i0 = out.index('page = f"""'); i1 = out.index('"""\nOUTP.write_text(page)')
PAGE = (HERE / "s3d_page_zh_template.txt").read_text()
out = out[:i0] + PAGE.rstrip("\n") + "\n" + out[i1:]
(HERE / "gen_s3d_page_zh.py").write_text(out)
print("wrote gen_s3d_page_zh.py;", len(R), "replacements")
